<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="FluentAssertions" Version="7.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="9.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="MockQueryable.NSubstitute" Version="10.0.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit.Analyzers" Version="3.9.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared.DataAccess\Shared.DataAccess.csproj" />
    <ProjectReference Include="..\Shared.Guardian\Shared.Guardian.csproj" />
    <ProjectReference Include="..\Shared.Logging\Shared.Logging.csproj" />
    <ProjectReference Include="..\Shared.Microservices\Shared.Microservices.csproj" />
    <ProjectReference Include="..\Shared.Security\Shared.Security.csproj" />
    <ProjectReference Include="..\Shared.Testing.Security\Shared.Testing.Security.csproj" />
    <ProjectReference Include="..\Shared.Services\Shared.Services.csproj" />
    <ProjectReference Include="..\Shared.Testing\Shared.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>